In [33]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import sklearn
import scipy as sp
import math
import matplotlib.pyplot as plt
pd.options.display.max_colwidth = 200
%matplotlib inline
#import contractions
import unicodedata
from numpy.random import seed
from numpy.random import randn
from statsmodels.graphics.gofplots import qqplot
#from matplotlib import pyplot
import pylab
from statsmodels.distributions.empirical_distribution import ECDF
from scipy.stats import norm
from scipy import stats
from statsmodels.stats.weightstats import ztest
from matplotlib import rcParams
import xlrd
import csv  
import os

In [38]:
f_1 = open(os.path.expanduser('~/Downloads/mercari/test.tsv'))

In [39]:
f_2 = open(os.path.expanduser('~/Downloads/mercari/train.tsv'))

In [40]:
df_1 = pd.read_csv(f_1, sep="\t")

In [45]:
df_1.columns

Index(['test_id', 'name', 'item_condition_id', 'category_name', 'brand_name',
       'shipping', 'item_description'],
      dtype='object')

In [46]:
df_1.dtypes

test_id               int64
name                 object
item_condition_id     int64
category_name        object
brand_name           object
shipping              int64
item_description     object
dtype: object

In [43]:
df_1.head()

test_id                                      name  item_condition_id  \
0        0  Breast cancer "I fight like a girl" ring                  1   
1        1  25 pcs NEW 7.5"x12" Kraft Bubble Mailers                  1   
2        2                                 Coach bag                  1   
3        3                             Floral Kimono                  2   
4        4                          Life after Death                  3   

                                    category_name brand_name  shipping  \
0                             Women/Jewelry/Rings        NaN         1   
1         Other/Office supplies/Shipping Supplies        NaN         1   
2  Vintage & Collectibles/Bags and Purses/Handbag      Coach         1   
3                         Women/Sweaters/Cardigan        NaN         0   
4             Other/Books/Religion & Spirituality        NaN         1   

                                                                                                                                                                                          item_description  
0                                                                                                                                                                                                   Size 7  
1  25 pcs NEW 7.5"x12" Kraft Bubble Mailers Lined with bubble wrap for protection Self Sealing (peel-and-seal), adhesive keeps contents secure and tamper proof Durable and lightweight Kraft material ...  
2                                                                                                                                                  Brand new coach bag. Bought for [rm] at a Coach outlet.  
3                                                                                                                                      -floral kimono -never worn -lightweight and perfect for hot weather  
4                                  Rediscovering life after the loss of a loved one by Tony Cooke. Paperback in good condition 2003. ❤ ❤ Bundle and save! ❤ ❤ Book, death, grief, bereavement SHLF.SW.5.15

In [49]:
df_1 = df_1.drop(['test_id'], axis=1)

In [50]:
df_1.head()

name  item_condition_id  \
0  Breast cancer "I fight like a girl" ring                  1   
1  25 pcs NEW 7.5"x12" Kraft Bubble Mailers                  1   
2                                 Coach bag                  1   
3                             Floral Kimono                  2   
4                          Life after Death                  3   

                                    category_name brand_name  shipping  \
0                             Women/Jewelry/Rings        NaN         1   
1         Other/Office supplies/Shipping Supplies        NaN         1   
2  Vintage & Collectibles/Bags and Purses/Handbag      Coach         1   
3                         Women/Sweaters/Cardigan        NaN         0   
4             Other/Books/Religion & Spirituality        NaN         1   

                                                                                                                                                                                          item_description  
0                                                                                                                                                                                                   Size 7  
1  25 pcs NEW 7.5"x12" Kraft Bubble Mailers Lined with bubble wrap for protection Self Sealing (peel-and-seal), adhesive keeps contents secure and tamper proof Durable and lightweight Kraft material ...  
2                                                                                                                                                  Brand new coach bag. Bought for [rm] at a Coach outlet.  
3                                                                                                                                      -floral kimono -never worn -lightweight and perfect for hot weather  
4                                  Rediscovering life after the loss of a loved one by Tony Cooke. Paperback in good condition 2003. ❤ ❤ Bundle and save! ❤ ❤ Book, death, grief, bereavement SHLF.SW.5.15

In [ ]:
df_2 = pd.read_csv(f_2, sep="\t")

In [51]:
df_2.columns

Index(['train_id', 'name', 'item_condition_id', 'category_name', 'brand_name',
       'price', 'shipping', 'item_description'],
      dtype='object')

In [52]:
df_2.dtypes

train_id               int64
name                  object
item_condition_id      int64
category_name         object
brand_name            object
price                float64
shipping               int64
item_description      object
dtype: object

In [53]:
df_2.head()


train_id                                 name  item_condition_id  \
0         0  MLB Cincinnati Reds T Shirt Size XL                  3   
1         1     Razer BlackWidow Chroma Keyboard                  3   
2         2                       AVA-VIV Blouse                  1   
3         3                Leather Horse Statues                  1   
4         4                 24K GOLD plated rose                  1   

                                        category_name brand_name  price  \
0                                   Men/Tops/T-shirts        NaN   10.0   
1  Electronics/Computers & Tablets/Components & Parts      Razer   52.0   
2                         Women/Tops & Blouses/Blouse     Target   10.0   
3                  Home/Home Décor/Home Décor Accents        NaN   35.0   
4                             Women/Jewelry/Necklaces        NaN   44.0   

   shipping  \
0         1   
1         0   
2         1   
3         1   
4         0   

                                                                                                                                                                               item_description  
0                                                                                                                                                                            No description yet  
1  This keyboard is in great condition and works like it came out of the box. All of the ports are tested and work perfectly. The lights are customizable via the Razer Synapse app on your PC.  
2                                                                  Adorable top with a hint of lace and a key hole in the back! The pale pink is a 1X, and I also have a 3X available in white!  
3                 New with tags. Leather horses. Retail for [rm] each. Stand about a foot high. They are being sold as a pair. Any questions please ask. Free shipping. Just got out of storage  
4                                                                                                                                                     Complete with certificate of authenticity

In [54]:
df_2 = df_2.drop(['train_id'], axis=1)


In [55]:
df_2.head()

name  item_condition_id  \
0  MLB Cincinnati Reds T Shirt Size XL                  3   
1     Razer BlackWidow Chroma Keyboard                  3   
2                       AVA-VIV Blouse                  1   
3                Leather Horse Statues                  1   
4                 24K GOLD plated rose                  1   

                                        category_name brand_name  price  \
0                                   Men/Tops/T-shirts        NaN   10.0   
1  Electronics/Computers & Tablets/Components & Parts      Razer   52.0   
2                         Women/Tops & Blouses/Blouse     Target   10.0   
3                  Home/Home Décor/Home Décor Accents        NaN   35.0   
4                             Women/Jewelry/Necklaces        NaN   44.0   

   shipping  \
0         1   
1         0   
2         1   
3         1   
4         0   

                                                                                                                                                                               item_description  
0                                                                                                                                                                            No description yet  
1  This keyboard is in great condition and works like it came out of the box. All of the ports are tested and work perfectly. The lights are customizable via the Razer Synapse app on your PC.  
2                                                                  Adorable top with a hint of lace and a key hole in the back! The pale pink is a 1X, and I also have a 3X available in white!  
3                 New with tags. Leather horses. Retail for [rm] each. Stand about a foot high. They are being sold as a pair. Any questions please ask. Free shipping. Just got out of storage  
4                                                                                                                                                     Complete with certificate of authenticity

In [56]:
df = df_2.append(df_1)

In [57]:
list(df)

['brand_name',
 'category_name',
 'item_condition_id',
 'item_description',
 'name',
 'price',
 'shipping']

In [58]:
df.columns

Index(['brand_name', 'category_name', 'item_condition_id', 'item_description',
       'name', 'price', 'shipping'],
      dtype='object')

In [59]:
df = df.reset_index(drop=True).head()

In [60]:
df.head()


brand_name                                       category_name  \
0        NaN                                   Men/Tops/T-shirts   
1      Razer  Electronics/Computers & Tablets/Components & Parts   
2     Target                         Women/Tops & Blouses/Blouse   
3        NaN                  Home/Home Décor/Home Décor Accents   
4        NaN                             Women/Jewelry/Necklaces   

   item_condition_id  \
0                  3   
1                  3   
2                  1   
3                  1   
4                  1   

                                                                                                                                                                               item_description  \
0                                                                                                                                                                            No description yet   
1  This keyboard is in great condition and works like it came out of the box. All of the ports are tested and work perfectly. The lights are customizable via the Razer Synapse app on your PC.   
2                                                                  Adorable top with a hint of lace and a key hole in the back! The pale pink is a 1X, and I also have a 3X available in white!   
3                 New with tags. Leather horses. Retail for [rm] each. Stand about a foot high. They are being sold as a pair. Any questions please ask. Free shipping. Just got out of storage   
4                                                                                                                                                     Complete with certificate of authenticity   

                                  name  price  shipping  
0  MLB Cincinnati Reds T Shirt Size XL   10.0         1  
1     Razer BlackWidow Chroma Keyboard   52.0         0  
2                       AVA-VIV Blouse   10.0         1  
3                Leather Horse Statues   35.0         1  
4                 24K GOLD plated rose   44.0         0

In [61]:
df.dtypes

brand_name            object
category_name         object
item_condition_id      int64
item_description      object
name                  object
price                float64
shipping               int64
dtype: object

In [62]:
df['category_name'].unique()

array(['Men/Tops/T-shirts',
       'Electronics/Computers & Tablets/Components & Parts',
       'Women/Tops & Blouses/Blouse',
       'Home/Home Décor/Home Décor Accents', 'Women/Jewelry/Necklaces'],
      dtype=object)

In [63]:
df['brand_name'].unique()

array([nan, 'Razer', 'Target'], dtype=object)

In [64]:
df['item_condition_id'].unique()

array([3, 1])

In [65]:
df['shipping'].unique()

array([1, 0])

In [66]:
df['price'].unique()

array([10., 52., 35., 44.])

In [67]:
df['category_name'].value_counts()

Women/Jewelry/Necklaces                               1
Electronics/Computers & Tablets/Components & Parts    1
Women/Tops & Blouses/Blouse                           1
Home/Home Décor/Home Décor Accents                    1
Men/Tops/T-shirts                                     1
Name: category_name, dtype: int64

In [68]:
df.size

35

In [69]:
df

brand_name                                       category_name  \
0        NaN                                   Men/Tops/T-shirts   
1      Razer  Electronics/Computers & Tablets/Components & Parts   
2     Target                         Women/Tops & Blouses/Blouse   
3        NaN                  Home/Home Décor/Home Décor Accents   
4        NaN                             Women/Jewelry/Necklaces   

   item_condition_id  \
0                  3   
1                  3   
2                  1   
3                  1   
4                  1   

                                                                                                                                                                               item_description  \
0                                                                                                                                                                            No description yet   
1  This keyboard is in great condition and works like it came out of the box. All of the ports are tested and work perfectly. The lights are customizable via the Razer Synapse app on your PC.   
2                                                                  Adorable top with a hint of lace and a key hole in the back! The pale pink is a 1X, and I also have a 3X available in white!   
3                 New with tags. Leather horses. Retail for [rm] each. Stand about a foot high. They are being sold as a pair. Any questions please ask. Free shipping. Just got out of storage   
4                                                                                                                                                     Complete with certificate of authenticity   

                                  name  price  shipping  
0  MLB Cincinnati Reds T Shirt Size XL   10.0         1  
1     Razer BlackWidow Chroma Keyboard   52.0         0  
2                       AVA-VIV Blouse   10.0         1  
3                Leather Horse Statues   35.0         1  
4                 24K GOLD plated rose   44.0         0

In [ ]:
df['category_name'].value_counts().head(15)

In [29]:
import csv

with open(r"C:\Users\nazanin.komeilizadeh\Downloads\mercari\test") as f:
    reader = csv.reader(f)
    for row in reader:
        print (row)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\nazanin.komeilizadeh\\Downloads\\mercari\\test'

In [30]:
f = open(r"C:\Users\nazanin.komeilizadeh\Downloads\mercari\test.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\nazanin.komeilizadeh\\Downloads\\mercari\\test.csv'

In [18]:
import os

from typing import List

path_dir: str = r"C:\Users\nazanin.komeilizadeh\Downloads\mercari\test"

content_dir: List[str] = os.listdir(path_dir)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\nazanin.komeilizadeh\\Downloads\\mercari\\test'

In [7]:
DIR= '\Users\nazanin.komeilizadeh\Downloads'

train_data = pd.read_csv(DIR+'/train.tsv', delimiter=',')
train_inputs = train_data.ix[:,0]
train_labels = train_data.drop(0, axis=1)
test_data = pd.read_csv(DIR+'/test.tsv', delimiter=',')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \UXXXXXXXX escape (<ipython-input-7-19b95367c1e5>, line 1)

In [32]:
df_b = pd.read_csv(r'C:\Users\nazanin.komeilizadeh\Downloads\mercari\test.csv', sep="\t")
df_b.head()

FileNotFoundError: [Errno 2] File b'C:\\Users\\nazanin.komeilizadeh\\Downloads\\mercari\\test.csv' does not exist: b'C:\\Users\\nazanin.komeilizadeh\\Downloads\\mercari\\test.csv'